Neos:
  Neos:
    fusion:
      autoInclude:
        "MhsDesign.LiveInspectorDomChange": true

  Fusion:
    defaultContext:
      Editable: MhsDesign\LiveInspectorDomChange\Fusion\Editable\Editable
